### ISSUE TITLE
Create New Business Sub-User Flow

### ISSUE THREAD

**Issue by adamcadaver** [narmi/oidc-demo#5]
# Create new Business sub-user (existing Lending Club User)

Step 4 follows the flow described in [existing user log in flow](https://github.com/narmi/oidc-demo/issues/2). At the end of the user creation flow in step 3 the user should be given a link that takes them through the log in flow or they should be redirected automatically.

```
+--------+                                   +--------+
| Narmi  |---(1) RegisterNarmiUser Request-->| OpenID |
|(Client)|                                   |Provider|
|        |<--(2) RegisterNarmiUser Response--|        |
|        |  +--------+                       |        |
|        |  |        |                       |        |
|        |  |  End-  |<--(3) AuthN & AuthZ-->|        |
|        |  |  User  |                       |        |
|   RP   |  |        |                       |   OP   |
|        |  +--------+                       |        |
|        |                                   |        |
|        |<------(4) Existing User Flow----->|        |
+--------+                                   +--------+
```
## Step 0
A **Business Owner** or **Admin** must go through the __create sub user flow__ within narmi. The **Owner/Admin** will provide a the sub user's:
- first name
- last name
- email
- phone

## 1) RegisterNarmiSubUser POST Request
```
POST /registerUser HTTP/1.1
  Host: server.example.com
  Content-Type: application/json
  content:
   {
    "client_id": "s6BhdRkqt3",                     # required
    "client_secret": "grw4shjg2",                  # required
    "sub: "24400322",                              # narmi uuid, required
    "institution_business_identifier": "2753222",  # used for finding the user in LC, required
    "email": "first.last@business.com",            # used for finding the user in LC, required
    "first_name": "first",                         # required
    "last_name": "last",                           # required
    "phone": "917-111-1111"                        # required
   }
```

## 2) RegisterNarmiUser POST Response
```
HTTP/1.1 201 Created
  Location: https://server.example.com/RegisterNarmiSubUser
```
In the case of an error here we will roll back user creation within Narmi

## 3) Register User in Lending Club
- Lending Club will send a the new sub user an email inviting them to create their user profile
- As part of that user creation process Lending Club can collect any information they require that it not provided via step 1.

## 4) Sub User Log in
Once the user has created their profile in Lending Club they can follow the standard [existing user log in flow](https://github.com/narmi/oidc-demo/issues/2).
